DIRECTORY:
  dataset: ./data/ #final_data #개발 경로에 맞게 수정하세요 !
  
TRAINER :
  model: deeplabv3p
  optimizer: adamw
  learning_rate: 1.0e-5
  n_epochs: 100
  early_stopping_target: val_mIoU
  early_stopping_patience: 10
  early_stopping_mode: max #min
  gpu: 0, 1
  seed: 42
  apply_aug: cutout
  weak_threshold: 0.7
  strong_threshold: 0.97
  apply_reco: True
  temp: 0.5
  num_queries: 256
  num_negatives: 512
  
MODEL:
  num_labels: 5
  output_dim: 256
  split_rate: 0.8

DATALOADER:
  batch_size: 8

LOGGER:
  wandb: True
  logging_interval: 100
  plot:
    - loss
    - mIoU
    - elapsed_time